# build environment
FROM node:17-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json .
COPY yarn.lock .
RUN yarn install --frozen-lockfile
RUN yarn global add react-scripts@5.0.0
COPY . .
ARG REACT_APP_BACKEND_SOCKET_URL
RUN yarn build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
